### ISSUE TITLE
how to broadcast message with tcp server?

### ISSUE THREAD

**Issue by luluxiuxiu** [retty-io/retty#6]
first,retty is very nice, but we have some a small problem,

how to broadcast message with tcp server? or exclude specific id?

and 

how to find any client context with tcp server?

or 

can be clone any inbound or outbound handlers to hashmap?

maybe we need socket handle map or uuid map?

**Comment by luluxiuxiu** [comment]
for game server ,we need find client context for close\write\boardcast\check, so,maybe we need some trait or function.

**Comment by yapprtc** [comment]
Thanks for the feedback. Let me add examples of broadcast sever or chat server to show how to use it.

**Comment by yapprtc** [comment]
https://github.com/retty-io/retty/releases/tag/v0.10.0 is released to change pipeline.finalize and PipelineFactoryFn to return Arc<Pipeline>.

examples/chat_tcp_server.rs shows how to do the broadcast message to other peers.
